### ISSUE TITLE
Add work with vibration motors

### ISSUE THREAD

**Issue by Greeka67** [jvpernis/esp32-ps3#17]
Hello.
Thank you so much for creating this library for the Arduino IDE.
Will vibration motor control be added?
Or maybe it is not described in the instructions?

**Comment by jvpernis** [comment]
Hi!

Support for the vibration motors are included in the newest version of this library (1.1.0). It also includes a sample sketch [Ps3Rumble](https://github.com/jvpernis/esp32-ps3/blob/master/examples/Ps3Rumble/Ps3Rumble.ino) which demonstrates how to use it.
